       IDENTIFICATION DIVISION.
           PROGRAM-ID. sqliteToDatafile.
       ENVIRONMENT DIVISION.
       INPUT-OUTPUT SECTION.
       FILE-CONTROL.
       DATA DIVISION.
       FILE SECTION.
       WORKING-STORAGE SECTION.
       LINKAGE SECTION.
       PROCEDURE DIVISION.
       SQLITETODATAFILE.
           EXIT PROGRAM.
       SQLITETODATAFILE-EXIT.
